### ISSUE TITLE
idea, unify sync/async code, use futures instead 

### ISSUE THREAD

**Issue by debris** [ethcore/jsonrpc#12]
@tomusdrw @rphmeier what do you think about that?

**Comment by tomusdrw** [comment]
Using futures in core will also make a strict requirements about transports (as far as I understand you need an event loop at some point to use futures), it's not bad per se, but might not be as simple as refactoring small part of the library.

(actually I think it might be better to write the whole `jsonrpc` from scratch instead of refactoring current one:))

**Comment by rphmeier** [comment]
It would be nice to have this as futures-based but given that we have 3 mediums of transport to support this might be a really significant undertaking.

**Comment by debris** [comment]
> Using futures in core will also make a strict requirements about transports (as far as I understand you need an event loop at some point to use futures)

Actually not. Futures might be easily used from tokio event loop, although using it is completely optional.

> It would be nice to have this as futures-based but given that we have 3 mediums of transport to support this might be a really significant undertaking.

We could take `tokio` for `tcp` and `http` (there is poc library called `minihttp-tokio`) or wait for tokio-based hyper release (afaik, it's on the roadmap). So the only transport that would have to be reimplemented is `ipc`
